mongo:
  pattern: /mongo
  defaults: { _controller: mongo_admin_controller:index }

mongo_server:
  pattern: /mongo/view/:server
  defaults: { _controller: mongo_admin_controller:viewServer }

mongo_db:
  pattern: /mongo/view/:server/:db
  defaults: { _controller: mongo_admin_controller:viewDb }

mongo_collection:
  pattern: /mongo/view/:server/:db/:collection
  defaults: { _controller: mongo_admin_controller:viewCollection }

mongo_document:
  pattern: /mongo/view/:server/:db/:collection/:id
  defaults: { _controller: mongo_admin_controller:viewDocument }